app/urls.py
from django.conf.urls import url
from django.http import HttpResponse

from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index')
]

music/urls.py
from django.conf.urls import url

from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    url(r'^register/$', views.UserFormView.as_view(), name = 'register'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'details'), #because it expects the primary key
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
    ]

proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from companies import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^stocks/', views.StockList.as_view()),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

music/models.py
from django.db import models
from django.urls import reverse

class Album(models.Model):

	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=1000)
	album_logo = models.FileField()

	def get_absolute_url(self):
		return reverse('music:details', kwargs={'pk': self.pk})

	def __str__(self):
		return self.artist + ' - ' + self.album_title


class Song(models.Model):

	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)

	def __str__(self):
		return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth import authenticate, login

from .forms import UserForm
from .models import Album


class IndexView(generic.ListView):
	# model = Album
	template_name = 'music/index.html'
	# context_object_name = 'list_of_albums'

	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model = Album
	template_name = 'music/details.html'

class AlbumCreate(CreateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
	model = Album
	success_url = reverse_lazy('music:index')

class UserFormView(View):
	form_class = UserForm
	template_name = 'music/registration_form.html'

	#display blank form
	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	#process form data
	def post(self, request):
		form = self.form_class(request.POST)
				
		if form.is_valid():

# it's just create object, but it doesn't save it in the data base actually
			user = form.save(commit=False)

			#cleaned (normalized) data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			#returns User objects if credentials are correct
			user = authenticate(username=username, password=password)

			if user is not None:

				if user.is_active:
					login(request, user)
					return redirect('music:index')

		return render(request, self.template_name, {'form': form})

templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active%}active{% endblock %}

{% block body %}
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token%}
		{% include 'music/form-template.html' %}
		<button type="submit">Submit</button>
{% endblock %}

templates/music/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
		{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static '/music/style.css' %}">
</head>
<body>
		<a href='{% url "music:index" %}'>Nikita</a><br>
							
{% block body %}
{% endblock %}

		<br><a href='{% url "music:album-add" %}'>Add album</a>
		

</body>
</html>

templates/music/details.html
{% extends 'music/base.html' %}

{% block title %}Details page{% endblock %}

{% block body %} 

<img src="{{ album.album_logo.url }}">

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

	{% for song in album.song_set.all %}
		{{ album.artist }} - {{ song.song_title }}<br>
	{% endfor %}
<a href='{% url "music:album-update" album.id %}'>Update album</a><br>
{% endblock %}

templates/music/form-template.html
{% for field in form %}
	{{ field.errors }}
	{{ field.label_tag }}
	{{ field }}<br>
{% endfor %}

templates/music/index.html
{% extends 'music/base.html' %}

{% block title %}Index page{% endblock %}

{% block body %} 

	{% if object_list %}
		<ul>
			{% for album in object_list %}
			<li>
				<a href="{% url 'music:details' album.id %}">{{ album.album_title }}</a>
				<form action="{% url 'music:album-delete' album.id %}" method="post">{% csrf_token %}
					<input type="submit" value="Delete" />
				</form>
				<a href='{% url "music:album-update" album.id %}'>Update album</a><br>
			</li>
			{% endfor %}
		</ul>
	{% else %}
		<h3>You don't have any albums</h3>
	{% endif %}

{% endblock %}